use std::{collections::HashMap, fs::File, io::Write, path::PathBuf};

use anyhow::Context;
use itertools::Itertools;
use rustc_hash::FxHashMap;

use crate::{
    diff::{Change, Compatibility, report::Diff},
    generate::CodeVersion,
    hist::classify::ClassifiedChanges,
};

use super::version::BiVersion;

pub struct HistCodegen {
    output_dir: PathBuf,
    version: CodeVersion,
}

impl HistCodegen {
    pub fn new(output_dir: PathBuf, version: CodeVersion) -> Self {
        Self {
            output_dir,
            version,
        }
    }

    pub fn generate_partial_versions(&mut self, changes: ClassifiedChanges) -> anyhow::Result<()> {
        for (version, changes) in changes.changed_by_version.iter() {
            self.write_partial_header(version, changes)?;
            self.write_partial_whitelist(version, changes)?;
        }
        Ok(())
    }

    fn write_partial_header(
        &mut self,
        version: &BiVersion,
        changes: &FxHashMap<String, Diff>,
    ) -> anyhow::Result<()> {
        let filename = match self.version {
            CodeVersion::Old => format!("partial-{}-to-{}.h", version.old, version.new),
            CodeVersion::New => format!("partial-{}-from-{}.h", version.new, version.old),
        };
        let path = self.output_dir.join(filename);
        let mut f = File::create(&path).with_context(|| format!("failed to create {path:?}"))?;
        writeln!(f, "/* generated by ch-hist */")?;

        let changes_by_compat: HashMap<Compatibility, Vec<(&String, &Diff)>> = changes
            .iter()
            .into_group_map_by(|(_, diff)| diff.semantic.compat());

        for (compat_level, changes) in changes_by_compat {
            writeln!(f, "\n{}", compat_comment(compat_level))?;

            for (name, diff) in changes {
                writeln!(f, "\n/* {name} */")?;
                match self.version {
                    CodeVersion::Old => writeln!(f, "{}", diff.source.old)?,
                    CodeVersion::New => writeln!(f, "{}", diff.source.new)?,
                }
            }
        }
        Ok(())
    }

    fn write_partial_whitelist(
        &self,
        version: &BiVersion,
        changes: &FxHashMap<String, Diff>,
    ) -> anyhow::Result<()> {
        let filename = match self.version {
            CodeVersion::Old => format!("whitelist-{}-to-{}.txt", version.old, version.new),
            CodeVersion::New => format!("whitelist-{}-from-{}.txt", version.new, version.old),
        };
        let path = self.output_dir.join(filename);
        let mut f = File::create(&path).with_context(|| format!("failed to create {path:?}"))?;

        for (name, _) in changes.iter().sorted_by_key(|(name, _)| name.to_owned()) {
            writeln!(f, "{name}")?;
        }

        Ok(())
    }
}

fn compat_comment(compat: Compatibility) -> &'static str {
    match compat {
        Compatibility::Breaking => "/* ========== (!) BREAKING CHANGES ========== */",
        Compatibility::Dubious => "/* ========== (?) DUBIOUS CHANGES ========== */",
        Compatibility::BackwardCompatible => {
            "/* ========== (~) BACKWARD-COMPATIBLE CHANGES ========== */"
        }
    }
}
