use std::{collections::HashMap, fs::File, io::Write, path::PathBuf};

use anyhow::Context;
use itertools::Itertools;

use crate::{
    diff::{Change, Compatibility, report::Diff},
    generate::CodeVersion,
    hist::classify::ClassifiedChanges,
};

pub struct HistCodegen {
    output_dir: PathBuf,
    version: CodeVersion,
}

impl HistCodegen {
    pub fn new(output_dir: PathBuf, version: CodeVersion) -> Self {
        Self {
            output_dir,
            version,
        }
    }

    pub fn generate_partial_version(&mut self, changes: ClassifiedChanges) -> anyhow::Result<()> {
        for (version, changes) in changes.changed_by_version.iter() {
            // create header file
            let filename = match self.version {
                CodeVersion::Old => format!("partial-{}-to-{}.h", version.old, version.new),
                CodeVersion::New => format!("partial-{}-from-{}.h", version.new, version.old),
            };
            let path = self.output_dir.join(filename);
            let mut f =
                File::create(&path).with_context(|| format!("failed to create {path:?}"))?;

            // header comment
            writeln!(f, "/* generated by ch-hist */")?;

            // write the code that has changed to the file
            let changes_by_compat: HashMap<Compatibility, Vec<(&String, &Diff)>> = changes
                .iter()
                .into_group_map_by(|(_, diff)| diff.semantic.compat());

            for (compat_level, changes) in changes_by_compat {
                writeln!(f, "\n{}", compat_comment(compat_level))?;

                for (name, diff) in changes {
                    writeln!(f, "\n/* {name} */")?;
                    match self.version {
                        CodeVersion::Old => writeln!(f, "{}", diff.source.old)?,
                        CodeVersion::New => writeln!(f, "{}", diff.source.new)?,
                    }
                }
            }
        }
        Ok(())
    }
}

fn compat_comment(compat: Compatibility) -> &'static str {
    match compat {
        Compatibility::Breaking => "/* ========== (!) BREAKING CHANGES ========== */",
        Compatibility::Dubious => "/* ========== (?) DUBIOUS CHANGES ========== */",
        Compatibility::BackwardCompatible => {
            "/* ========== (~) BACKWARD-COMPATIBLE CHANGES ========== */"
        }
    }
}
